---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: paulfdunn/rest-app/example:v0.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: "/opt/example/data"
          name: data
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: example-pvc
