---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  labels:
    app: example
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/example/data
    server: ec2-3-16-163-139.us-east-2.compute.amazonaws.com